export const projects = [
  {
    title: 'Chapters Social Media App',
    description: "This project is a Social Media full MERN Stack application called Chapters. Here you can post anything you want to, upload pictures with your post, give and receive likes, leave hash tags on post, and delete any posts you feel embarrassed about.",
      image: '/images/chapters.jpg',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/Aswebilius/chapters',
    visit: 'https://project-3-chapters.netlify.app/',
    id: 0,
  },
  {
    title: 'Real Estate Xpress App',
    description:"A Real Estate Search Application that utilizes RapidAPI’s Bayut API to locate properties for both rent and sale. The application features advanced property filtering, detailed property information, and image carousel when viewing properties.",
    image: '/images/realEstate.jpg',
    tags: ['React', 'NextJS', 'RapidAPI/BayutAPI', 'Chakra UI'],
    source: 'https://github.com/Aswebilius/real-estate-xpress',
    visit: 'https://real-estate-xpress-gkd5z808d-aswebilius.vercel.app/',
    id: 1,
  },
  {
    title: 'Budget Tracker PWA',
    description: "This application is a simple way for the User to track inflows and outflows in their finances. The information is displayed with a graph that will track by date and visually display the information.",
    image: '/images/budgetTracker.jpg',
    tags: ['HTML','Mongo', 'Mongoose', 'ExpressJS'],
    source: 'https://github.com/Aswebilius/PWA-Budget-Tracker',
    visit: 'https://aswebilius-pwa-budget-tracker.herokuapp.com/',
    id: 2,
  },
  // {
    //   title: 'Chatter Box',
    //   description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    //   image: '/images/noteTaker.jpg',
    //   tags: ['React', 'ChatEngine', 'Firebase'],
    //   source: 'https://google.com',
    //   visit: 'https://google.com',
    //   id: 3,
    // },
    {
      title: 'Real Time Weather Application',
      description: "This Weather application will display the current weather in real time along with a color coded UV Index to warn you of extreme UV exposure.",
      image: '/images/realWeather.jpg',
      tags: ['HTML', 'CSS', 'JQuery', 'Weather API'],
      source: 'https://github.com/Aswebilius/Real-Time-Weather-App',
      visit: 'https://aswebilius.github.io/Real-Time-Weather-App/',
      id: 4,
    },
    {
      title: 'Note Taker App',
      description: "This Note Taker Application. The User can write a note in the fields provided and then save it.",
      image: '/images/noteTaker.jpg',
      tags: ['JavaScript', 'NodeJS'],
      source: 'https://github.com/Aswebilius/note-taker',
      visit: 'https://aswebilius-note-taker.herokuapp.com/',
      id: 5,
    },
    {
      title: 'MyVids YouTube Clone App',
      description: "This application is a YouTube clone created by using ReactJS and the Google YouTube API.",
        image: '/images/myVids.jpg',
        tags: ['React','Google YouTube API'],
      source: 'https://github.com/Aswebilius/my-vids',
      visit: 'https://myvids-react-youtube-clone.netlify.app/',
      id: 6,
    },
    {
      title: 'Run Buddy Home Page',
      description: "This is a mock landing page for the fake Run Buddy website designed and implemented as part of the UCF FullStack Developer Bootcamp. This page is a demonstration of basic competencies in HTML and CSS coding.",
      image: '/images/runBuddy.jpg',
      tags: ['HTML', 'CSS'],
      source: 'https://github.com/Aswebilius/run-buddy',
      visit: 'https://aswebilius.github.io/run-buddy/',
      id: 7,
    },
];

export const TimeLineData = [
  { year: 2016, text: "Graduated with my Bachelor of Science degree in Computer Science", },
  { year: 2017, text: "Worked as an IT Specialist", },
  { year: 2020, text: "Graduated the Daytona State College Police Academy", },
  { year: 2021, text: "Graduated the UCF's FullStack Web Developer Bootcamp", },
  { year: 2022, text: "Will graduate from Purdue Global University with a Masters in Business Administration with a specialization in Information Technology", }
];